# Generated by Django 4.2 on 2023-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('sur_name', models.TextField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=1, max_length=10)),
            ],
        ),
    ]
